In [39]:
import pandas as pd
import numpy as np

my_file = "master_ref_set.csv" #insert file name here, should be in same directory if no file path
df = pd.read_csv(my_file)

# Create index and sample dataframes
index_df = df.drop(df.columns[2:], axis=1) 
sample_df = df.drop(df.columns[0:2], axis=1)

countif = 0

      
for i in range(1,101): #can change 101 to whatever number of output files you need
    countif = str(i)
    outfilename = countif + "_result.csv" # can change _result to whatever file name you desire
    random_df = sample_df.sample(n=10, axis=1) # n=10 denotes how many random samples to pull
    res_df = pd.concat([index_df,random_df], axis=1)
    res_df.to_csv(outfilename, index=True)
    #res_df.to_csv('random_"countif".csv', index=True)
   

res_df.head() #displays below, so you know this worked

,gene_short_name,V515-06187-A1,TNT-289,TNT-209,TNT-4,TNT-18,TNT-104,TNT-14,17-00112-1_S7_cufflinks,TNT-35,17-00132-8_S16Aligned_cufflinks,TNT-3
0,ABCA8,1.073970,7.532600,5.75345,37.71850,10.562900,45.001100,1.686790,0.000000,16.629100,19.42480,10.63470
1,ADRA2A,0.196819,0.019086,1.18075,4.02106,0.337047,0.026928,0.104517,0.403755,0.981889,3.61611,0.00000
2,AKAP12,3.752430,16.451800,5.17876,17.72070,10.105500,14.878700,2.160440,1.658670,12.766900,5.52166,4.93901
3,ALDH3B2,34.613000,0.340181,5.19828,42.56990,1.590880,134.500000,5.566070,5.143960,73.376000,6.77506,0.00000
4,APOD,101.548000,86.534300,12.39610,2583.61000,126.366000,16699.300000,10.927700,1.083720,4574.950000,40.37400,4.43815