In [176]:
import pandas as pd
import numpy as np
#read in master file
my_file = "master_ref_set.csv" #input tsv or csv
df = pd.read_csv(my_file)
#set indexes
df.set_index(['gene_short_name', 'V515-06187-A1'])
df.head()

,gene_short_name,V515-06187-A1,TNT-1,TNT-2,TNT-3,TNT-4,TNT-6,TNT-8,TNT-13,TNT-14,...,17-00212-8_S3Aligned_cufflinks,17-00214-4_S8Aligned_cufflinks,17-00243-6_S9Aligned_cufflinks,17-00252-2_S13Aligned_cufflinks,17-00258-5_S5Aligned_cufflinks,17-00269-8_S12Aligned_cufflinks,17-00270-5_S14Aligned_cufflinks,17-00271-8_S16Aligned_cufflinks,17-00280-7_S4Aligned_cufflinks,17-00283-0_S6Aligned_cufflinks
0,ABCA8,1.073970,47.343500,11.342400,10.63470,37.71850,9.65740,21.135300,26.68400,1.686790,...,10.90080,11.971600,39.57720,10.100600,6.536240,10.575400,2.109630,43.17190,1.961040,13.751200
1,ADRA2A,0.196819,0.120636,0.725975,0.00000,4.02106,1.35793,0.398157,0.00000,0.104517,...,0.80400,0.345093,2.18221,0.666199,0.656837,0.231559,0.785147,3.57135,0.330945,0.841984
2,AKAP12,3.752430,4.009060,4.330160,4.93901,17.72070,11.31200,2.997650,11.31620,2.160440,...,6.45585,3.783270,18.63050,3.591530,3.789710,3.770410,3.936420,19.81290,1.989680,12.129700
3,ALDH3B2,34.613000,8.465570,59.863300,0.00000,42.56990,433.61300,2.430560,8.65127,5.566070,...,54.54060,2.575870,6.11671,57.073700,0.884181,3.695380,173.954000,111.37600,75.895900,1.868770
4,APOD,101.548000,6.437400,61.014900,4.43815,2583.61000,13601.30000,223.767000,194.97200,10.927700,...,1024.91000,26.839100,222.14700,2264.750000,70.123200,55.152100,1702.360000,1551.18000,25.213700,91.025400

In [178]:
#select random samples
random = df.sample(n=10, random_state=90,axis=1) 
df2 = pd.DataFrame.from_dict(random)#.insert(1, 'gene_short_name', 1)
df2.head()

,TNT-27,TNT-6,TNT-300,17-00258-5_S5Aligned_cufflinks,TNT-57,TNT-139,17-00097-1_S9_cufflinks,TNT-234,TNT-73,17-00099-0_S15_cufflinks
0,1.91007,9.65740,2.023420,6.536240,6.469010,4.219020,2.107500,4.492780,7.785460,2.37642
1,0.00000,1.35793,0.019426,0.656837,0.408656,0.358636,0.130515,0.631742,0.224004,1.09600
2,4.47033,11.31200,1.303590,3.789710,6.260160,4.574510,1.870440,13.175800,6.591720,3.23311
3,0.00000,433.61300,11.256800,0.884181,0.100817,4.680610,8.435540,1.062070,8.950570,15.29870
4,12.37540,13601.30000,4.160830,70.123200,51.891900,1392.610000,0.669381,158.972000,2468.970000,3.69936

In [179]:
#print to new file with name x. Need to include first two columns. 
df2.to_csv('random_10.csv', index=True)
result_file = "random_7.csv"
res = pd.read_csv(result_file)
res.head()

,Unnamed: 0,TNT-211,TNT-227,TNT-166,TNT-113,TNT-8,TNT-318,TNT-265,17-00113-4_S11_cufflinks,TNT-2,TNT-282
0,0,61.290100,0.876496,8.041940,6.80200,21.135300,1.60268,2.632550,15.30240,11.342400,4.677020
1,1,0.395498,0.949996,0.172444,1.08531,0.398157,0.37137,0.860494,1.17333,0.725975,0.018128
2,2,10.402400,4.588480,11.417600,12.11450,2.997650,7.96738,4.094340,3.48712,4.330160,3.379910
3,3,1.135340,0.000000,11.936000,4.95691,2.430560,1.01293,7.944780,0.00000,59.863300,14.249200
4,4,44.836000,13.734500,59.251500,207.70900,223.767000,29.28450,3.243890,364.67200,61.014900,1.374450