In [2]:
import pandas as pd
import numpy as np

my_file = "master_ref_set.csv" #insert file name here, should be in same directory if no file path
df = pd.read_csv(my_file)

# Create index and sample dataframes
index_df = df.drop(df.columns[2:], axis=1) 
sample_df = df.drop(df.columns[0:2], axis=1)

countif = 0

      
for i in range(1,101): #can change 101 to whatever number of output files you need
    countif = str(i)
    outfilename = countif + "_result.csv" # can change _result to whatever file name you desire
    random_df = sample_df.sample(n=10, axis=1) # n=10 denotes how many random samples to pull
    res_df = pd.concat([index_df,random_df], axis=1)
    res_df.to_csv(outfilename, index=False)
    #res_df.to_csv('random_"countif".csv', index=True)
   

res_df.head() #displays below, so you know this worked

,gene_short_name,V515-06187-A1,17-00243-6_S9Aligned_cufflinks,17-00140-2_S2_cufflinks,TNT-192,TNT-297,TNT-259,17-00132-8_S16Aligned_cufflinks,17-00258-5_S5Aligned_cufflinks,TNT-111,TNT-278,TNT-310
0,ABCA8,1.073970,39.57720,4.180900,119.155000,17.017400,7.378800,19.42480,6.536240,14.85620,6.09487,1.506030
1,ADRA2A,0.196819,2.18221,0.974128,0.801336,0.223559,0.062241,3.61611,0.656837,1.03917,0.00000,0.091635
2,AKAP12,3.752430,18.63050,1.052790,35.966200,31.172200,10.407800,5.52166,3.789710,15.70740,4.77909,5.489900
3,ALDH3B2,34.613000,6.11671,25.780500,68.192800,0.091029,2.398880,6.77506,0.884181,575.45300,1.87834,18.729900
4,APOD,101.548000,222.14700,4.293170,11869.700000,190.081000,16.172500,40.37400,70.123200,10225.50000,86.31320,9.072700