In [1]:
import pandas as pd
import numpy as np

my_file = "master_ref_set.csv" #insert file name here, should be in same directory if no file path
df = pd.read_csv(my_file)

# Create index and sample dataframes
index_df = df.drop(df.columns[2:], axis=1) 
sample_df = df.drop(df.columns[0:2], axis=1)

countif = 0

      
for i in range(1,101): #can change 101 to whatever number of output files you need
    countif = str(i)
    outfilename = "sample_result_n100_" + countif + ".csv" # can change _result to whatever file name you desire
    random_df = sample_df.sample(n=10, axis=1) # n=10 denotes how many random samples to pull
    res_df = pd.concat([index_df,random_df], axis=1)
    res_df.to_csv(outfilename, index=True)
    #res_df.to_csv('random_"countif".csv', index=True)
   

res_df.head() #displays below, so you know this worked

,gene_short_name,V515-06187-A1,TNT-50,17-00111-2_S4_cufflinks,TNT-197,TNT-113,TNT-111,TNT-271,TNT-192,TNT-252,17-00113-4_S11_cufflinks,TNT-297
0,ABCA8,1.073970,6.270590,3.13612,3.134170,6.80200,14.85620,19.301900,119.155000,8.545730,15.30240,17.017400
1,ADRA2A,0.196819,0.613286,1.38168,0.245942,1.08531,1.03917,0.104250,0.801336,0.303387,1.17333,0.223559
2,AKAP12,3.752430,15.719300,6.91818,8.951210,12.11450,15.70740,9.758690,35.966200,3.341930,3.48712,31.172200
3,ALDH3B2,34.613000,19.422100,7.41563,1.981310,4.95691,575.45300,0.048504,68.192800,0.000000,0.00000,0.091029
4,APOD,101.548000,34.866100,53.91980,62.484700,207.70900,10225.50000,18.801900,11869.700000,7.803390,364.67200,190.081000